name: notes_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_staggered_grid_view: ^0.7.0
  leak_tracker: ^10.0.4
  leak_tracker_flutter_testing: 3.0.3
  lints: ^4.0.0
  intl: ^0.17.0
  image_picker: ^0.8.4+8
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  # Firebase and Google Sign-In dependencies
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  google_sign_in: ^6.1.4
  sign_in_button: ^3.2.0

dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
